
name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        repository: windytan/redsea.git
        path: main   

    - name: install
      run:  sudo apt install build-essential autoconf

    - name: autogen
      run: |
            docker run --rm dockcross/windows-shared-x86 > ./xcross; chmod +x ./xcross; sudo mv ./xcross /usr/bin/
            cd /home/runner/work/dockcross-test3/dockcross-test3/main
            wget 'https://github.com/cjcliffe/CubicSDR/raw/master/external/liquid-dsp/gcc/32/libliquid.a'
            wget 'https://github.com/cjcliffe/CubicSDR/raw/master/external/liquid-dsp/gcc/32/libliquid.dll'
            wget 'http://repo.msys2.org/mingw/i686/mingw-w64-i686-libsndfile-1.0.28-1-any.pkg.tar.xz'
            tar xvf mingw-w64-i686-libsndfile-1.0.28-1-any.pkg.tar.xz
            ls
            xcross ./autogen.sh 
            ls
            xcross env LDFLAGS="-L./ -L./mingw32/lib/" ./configure --host=i386-pc-mingw32
            ls
            xcross make
            ls -la src/

